language: go
go:
  - 1.6.x
  - 1.7.x
sudo: false

script:
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  
install:
  - git clone https://github.com/bitgo/prova $GOPATH/src/github.com/bitgo/prova
  - cd $GOPATH/src/github.com/bitgo/prova
  - go get -u github.com/Masterminds/glide
  - glide install
  - go install . ./cmd/...
